Fix MDX node types
syntax-tree/hast-util-to-estree pull request #4
Opened 2021-07-11 12:00 UTC by remcohaszing

### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

- In `MDXJsxAttributeValueExpression`, `value` is optional.
- The `data` property of `MDXJsxAttributeValueExpression` is an estree program.
- In `MDXJsxAttribute`, `value` is optional.
- In `MDXEsm`, `value` is optional.

2021-07-11 13:10 UTC, ChristianMurphy requested changes
Thanks @remcohaszing!
When you have a chance could you take a look at the test suite?
After this change it appears to be failing with type errors. :thinking:

2021-07-11 13:30 UTC, remcohaszing commented
The errors are caused by DefinitelyTyped/DefinitelyTyped#54181, not by this PR. I’m fixing it though.

2021-07-11 13:40 UTC, wooorm reviewed
looks good to me other than the existing error!

2021-07-11 13:47 UTC, remcohaszing commented
That having said, I have to go AFK now. I’ll fix it later.

2021-08-15 14:36 UTC, wooorm commented
@remcohaszing It’s later now!

Note that we could also pull the types in from `mdast-util-mdx`? https://github.com/syntax-tree/mdast-util-mdx/commit/45365a22a95cfeb63dcbc6bfe493bb392f01860d

2021-08-15 19:22 UTC, remcohaszing commented
I rebased and force pushed. The imports also fix the type issues that were fixed in the original commit.

2021-08-15 19:30 UTC, ChristianMurphy approved these changes
LGTM, thanks @remcohaszing!

2021-08-16 08:53 UTC, wooorm approved these changes

2021-08-16 08:53 UTC, merged

2021-08-16 08:56 UTC, wooorm commented
Released! https://github.com/syntax-tree/hast-util-to-estree/releases/tag/2.0.1